# Generated by Django 4.1.3 on 2022-11-05 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('sale', 'Sale'), ('rent', 'Rent')], max_length=100)),
                ('property_type', models.CharField(choices=[('homes', 'Homes'), ('plots', 'Plots'), ('commercial', 'Commercial')], max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=100)),
                ('area', models.IntegerField(default='')),
                ('bedrooms', models.IntegerField(default=0)),
                ('bathrooms', models.IntegerField(default=0)),
                ('listing_expiry', models.IntegerField(default=0)),
                ('monthly_rent', models.IntegerField(default=0)),
                ('advance_rent', models.IntegerField(default=0)),
                ('contact_person', models.CharField(default='', max_length=100)),
                ('contact_person_email', models.CharField(default='', max_length=100)),
                ('contact_person_phone', models.CharField(default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.agent')),
            ],
        ),
    ]
